CREATE TABLE medications
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    patient_id      BIGINT                                  NOT NULL,
    medication_name VARCHAR(255)                            NOT NULL,
    dosage          VARCHAR(255)                            NOT NULL,
    frequency       VARCHAR(255)                            NOT NULL,
    start_date      date                                    NOT NULL,
    end_date        date,
    prescribed_by   VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_medications PRIMARY KEY (id)
);

ALTER TABLE medications
    ADD CONSTRAINT FK_MEDICATIONS_ON_PATIENT FOREIGN KEY (patient_id) REFERENCES patients (id);