CREATE TABLE measures
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name                VARCHAR(255)                            NOT NULL,
    description         VARCHAR(255)                            NOT NULL,
    scheduled_date_time TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    is_completed        BOOLEAN                                 NOT NULL,
    goal_id             BIGINT                                  NOT NULL,
    CONSTRAINT pk_measures PRIMARY KEY (id)
);

ALTER TABLE measures
    ADD CONSTRAINT FK_MEASURES_ON_GOAL FOREIGN KEY (goal_id) REFERENCES goals (id);