CREATE TABLE patient_diagnoses
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    patient_id   BIGINT                                  NOT NULL,
    code         VARCHAR(20)                             NOT NULL,
    is_primary   BOOLEAN                                 NOT NULL,
    description  VARCHAR(255)                            NOT NULL,
    diagnosed_at date                                    NOT NULL,
    diagnosed_by VARCHAR(30)                             NOT NULL,
    CONSTRAINT pk_patient_diagnoses PRIMARY KEY (id)
);

ALTER TABLE patient_diagnoses
    ADD CONSTRAINT FK_PATIENT_DIAGNOSES_ON_PATIENT FOREIGN KEY (patient_id) REFERENCES patients (id);