CREATE TABLE goals
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255)                            NOT NULL,
    description VARCHAR(255)                            NOT NULL,
    patient_id  BIGINT                                  NOT NULL,
    CONSTRAINT pk_goals PRIMARY KEY (id)
);

ALTER TABLE goals
    ADD CONSTRAINT FK_GOALS_ON_PATIENT FOREIGN KEY (patient_id) REFERENCES patients (id);