CREATE TABLE care_plans
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    patient_id BIGINT                                  NOT NULL,
    notes      VARCHAR(255),
    CONSTRAINT pk_care_plans PRIMARY KEY (id)
);

ALTER TABLE care_plans
    ADD CONSTRAINT uc_care_plans_patient UNIQUE (patient_id);

ALTER TABLE care_plans
    ADD CONSTRAINT FK_CARE_PLANS_ON_PATIENT FOREIGN KEY (patient_id) REFERENCES patients (id);