CREATE TABLE patients
(
    id         BIGINT NOT NULL,
    first_name VARCHAR(255),
    last_name  VARCHAR(255),
    birth_date date,
    gender     VARCHAR(255),
    address    VARCHAR(255),
    identifier VARCHAR(255),
    user_id    BIGINT,
    CONSTRAINT pk_patients PRIMARY KEY (id)
);

ALTER TABLE patients
    ADD CONSTRAINT FK_PATIENTS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);
CREATE TABLE patients
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    first_name      VARCHAR(255)                            NOT NULL,
    last_name       VARCHAR(255)                            NOT NULL,
    birth_date      VARCHAR(255)                            NOT NULL,
    gender          VARCHAR(20)                             NOT NULL,
    address         VARCHAR(255)                            NOT NULL,
    email           VARCHAR(255)                            NOT NULL,
    phone           VARCHAR(255)                            NOT NULL,
    identifier      BIGINT                                  NOT NULL,
    organization_id BIGINT,
    CONSTRAINT pk_patients PRIMARY KEY (id)
);

ALTER TABLE patients
    ADD CONSTRAINT uc_patients_email UNIQUE (email);

ALTER TABLE patients
    ADD CONSTRAINT uc_patients_identifier UNIQUE (identifier);

ALTER TABLE patients
    ADD CONSTRAINT uc_patients_phone UNIQUE (phone);
CREATE TABLE patients
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    first_name      VARCHAR(255)                            NOT NULL,
    last_name       VARCHAR(255)                            NOT NULL,
    birth_date      VARCHAR(255)                            NOT NULL,
    gender          VARCHAR(20)                             NOT NULL,
    address         VARCHAR(255)                            NOT NULL,
    email           VARCHAR(255)                            NOT NULL,
    phone           VARCHAR(255)                            NOT NULL,
    identifier      BIGINT                                  NOT NULL,
    organization_id BIGINT,
    CONSTRAINT pk_patients PRIMARY KEY (id)
);

ALTER TABLE patients
    ADD CONSTRAINT uc_patients_email UNIQUE (email);

ALTER TABLE patients
    ADD CONSTRAINT uc_patients_identifier UNIQUE (identifier);

ALTER TABLE patients
    ADD CONSTRAINT uc_patients_phone UNIQUE (phone);