CREATE TABLE organizations
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_organizations PRIMARY KEY (id)
);

ALTER TABLE organizations
    ADD CONSTRAINT uc_organizations_name UNIQUE (name);